name: chicki_buddy
description: A Voice AI Assistant using Flutter and GPT

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Voice Services
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  sherpa_onnx: ^1.12.14  # Text-to-speech with ONNX models
  permission_handler: ^11.0.1  # Added permission handler
  porcupine_flutter: ^3.0.3  # Wake word detection

  # HTTP and API
  http: ^1.2.0
  dio: ^5.4.0

  # State Management
  get: ^4.6.6

  # Utils
  logger: ^2.0.2
  translator: ^1.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.2.1

  # UI
  flutter_animate: ^4.5.0

  # Media
  image_picker: ^1.0.7

  # Android Foreground Service
  flutter_foreground_task: ^8.17.0
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  go_router: ^16.2.2
  moon_design: ^1.1.0
  waveform_flutter: ^1.2.0
  dart_openai: ^5.1.0
  vertical_card_pager: ^1.6.3
  audioplayers: ^6.5.1
  path: ^1.9.1
  lucide_icons: ^0.257.0
  mesh_gradient: ^1.3.8
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  android_id: ^0.4.0
  json_serializable: ^6.9.0
  auto_size_text: ^3.0.0
  just_audio: ^0.10.5
  flutter_sound: ^9.29.13
  openai_realtime_dart: ^0.1.0+1
  rive: ^0.14.0-dev.6
  iconify_flutter: ^0.0.7
  archive: ^4.0.7
  tflite_flutter: ^0.12.1
  # media_kit: ^1.2.0
  # media_kit_libs_audio: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/chicky.riv
    - assets/vocab/books.json
    - assets/data/graph.json
    - assets/icon.png

    - assets/models/model.tflite
    - assets/models/vocab.txt
    - assets/models/intent_mapping.json

    - assets/vits-piper-en_GB-jenny_dioco-medium/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/aav/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/art/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/azc/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/bat/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/bnt/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/ccs/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/cel/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/cus/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/dra/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/esx/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/gmq/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/gmw/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/grk/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/inc/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/ine/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/ira/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/iro/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/itc/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/jpx/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/map/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/miz/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/myn/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/poz/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/roa/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/sai/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/sem/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/sit/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/tai/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/trk/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/urj/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/zle/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/zls/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/lang/zlw/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/voices/
    - assets/vits-piper-en_GB-jenny_dioco-medium/espeak-ng-data/voices/!v/

    - assets/hey_chicky.ppn
    - assets/overlay.jpg
    - assets/black_overlay.jpg
    - assets/avatar/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf